### ISSUE TITLE
External_Transform never called

### ISSUE THREAD

**Issue by Xqua** [mpicbg-scicomp/snakemake-workflows#23]
Hi, for some reason the rule external transform is never called !

It leads to some error, but most importantly I can't Downsample prior to deconvolution. 
I need to get the merge.XML file, apply the transform by hand (sed) and then launch again the deconvolution. 

I'm not sure why this is the case, I've tried to parse out why it never calls this rule but cannot figure it out ...  

## Logs 
```wildcard constraints in inputs are ignored
wildcard constraints in inputs are ignored
wildcard constraints in inputs are ignored
wildcard constraints in inputs are ignored
wildcard constraints in inputs are ignored
wildcard constraints in inputs are ignored
Provided cluster nodes: 2
Job counts:
	count	jobs
	2	deconvolution
	1	define_output
	1	define_xml_czi
	1	done
	1	hdf5_xml
	1	hdf5_xml_output
	2	registration
	2	resave_hdf5
	2	resave_hdf5_output
	1	xml_merge
	14```

**Comment by schmiedc** [comment]
Hi,

I will look into it. Could you send me the config.yaml you are using? 

Cheers,
Christopher

**Comment by psteinb** [comment]
Is this problem still there? If so, can you send us a `ls` output of the directory you are working in and the config.yaml you are using to provoke this bahvior.

**Comment by Xqua** [comment]
I can't reproduce this now, and I've trashed the config file for that dataset. But I did not run into this error again so I'll assume it was my fault !
