### ISSUE TITLE
sbatch: error: invalid partition specified: cpu

### ISSUE THREAD

**Issue by mcahn** [mpicbg-scicomp/snakemake-workflows#24]
I'm attempting to get the workflow running on our cluster of GPU nodes.  A few steps seem to run, but when I get to the fusion rule, I get the output below.  The cluster uses the SLURM queueing system.  It seems that SLURM thinks the workflow is asking for the "cpu" partition of the cluster, which does not exist.

Our cluster has one partition, called "gpu".  Normally, failing to specify any GPU's in the SLURM request results in a failed submission to the "serial" partition, so I'm really not clear on where "cpu" is coming from.  I'm also unable to get snakemake to display the sbatch command being issued.

Any help would be appreciated.

Best,
Matthew Cahn

wildcard constraints in inputs are ignored
wildcard constraints in inputs are ignored
wildcard constraints in inputs are ignored
wildcard constraints in inputs are ignored
wildcard constraints in inputs are ignored
wildcard constraints in inputs are ignored
Provided cluster nodes: 2
Job counts:
	count	jobs
	1	define_output
	1	done
	1	fusion
	1	hdf5_xml_output
	1	resave_hdf5_output
	5

rule fusion:
    input: dataset_one_merge.xml_timelapse, dataset_one-00-00.h5, dataset_one_merge.xml
    output: dataset_one-00-00.h5_fusion
    log: logs/e1_dataset_one-00-00-fusion.log
    jobid: 4
    wildcards: xml_base=dataset_one, file_id=00

sbatch: error: invalid partition specified: cpu
sbatch: error: Batch job submission failed: Invalid partition name specified
Error submitting jobscript (exit code 1):

Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /tigress/mcahn/snakemake-workflows/spim_registration/timelapse/.snakemake/log/2017-10-10T173521.169101.snakemake.log

**Comment by schmiedc** [comment]
Dear Matthew Cahn,

only the multiview deconvolution and the difference-of-gaussian bead detection are actually GPU accelerated. 

For both you also require libraries that you need to compile specifically for your system. 
For the deconvolution: https://github.com/StephanPreibisch/FourierConvolutionCUDALib
Difference-of-gaussian: https://github.com/StephanPreibisch/SeparableConvolutionCUDALib

I would suggest try to make it run on a local system with the GUI (using the Fiji version provided in the wiki) and then move to the cluster workflow. 

Cheers,
Christopher

**Comment by mcahn** [comment]
Hi Christopher,

Thanks for your reply.  I understand only certain steps of the workflow are GPU-accelerated.  Nevertheless our objective is to run the whole workflow on this particular cluster.  Steps that are not GPU accelerated can still run on the CPU's of the compute nodes.  If there are any steps that the workflow does not submit to slurm, they can even run on the login node (if they're short).

So it would still be very helpful to know if there's a way to see what command the workflow is submitting.  If the workflow can't submit a non-GPU step to slurm, it won't be able to submit a GPU step either.  The way it fails, slurm does not even attempt to start the job -- it's immediately rejected by the script that slurm runs to choose queues and other parameters -- and there's no record of what the failed command was.

Best,
Matthew

**Comment by schmiedc** [comment]
Hi Matthew,

ah ok, I think I get it now. It seems that you have a problem with snakemake itself interacting with your cluster queuing system. As far as I remember when executing the workflow a temporary directory .snakemake will be created that contains the job scripts that are sent to the queueing system. This is where this log file went for example:  /tigress/mcahn/snakemake-workflows/spim_registration/timelapse/.snakemake/log/2017-10-10T173521.169101.snakemake.log

Possible that your cluster.json is not properly configured for the fusion step. Could you post this script so @psteinb and me could review it? 

For proper configuration of the cluster.json please refer to: http://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html

Cheers,
Christopher

**Comment by mcahn** [comment]
The log file doesn't contain the information I was looking for, which is what exactly was submitted to slurm.  But I've fixed my problem.  Specifying how many GPU's to use in the fusion rule in cluster.json causes our cluster to submit to the right partition.  (It doesn't matter that the fusion step doesn't use GPU's.  This cluster requires a GPU specification, or it complains about a non-existent partition.  Confusingly, the partition name it complains about is different than I expected, so I thought the incorrect partition was specified by the workflow -- but it isn't, it's our slurm configuration that's making up the wrong name).

Thanks very much for your help.

Best,
Matthew

**Comment by schmiedc** [comment]
Hi Matthew,

glad it works for you. Thanks for letting me now what the problem was.

Best,
Christopher

**Comment by psteinb** [comment]
@mcahn if this problem is solved, please consider closing this issue.
