### ISSUE TITLE
file timelapsedefine_czi.bsh missing?

### ISSUE THREAD

**Issue by psteinb** [mpicbg-scicomp/snakemake-workflows#26]
I was just following the [wiki](http://imagej.net/Automated_workflow_for_parallel_Multiview_Reconstruction) and got this when sending a job on the exampleData:

```
File not found: java.io.FileNotFoundException: /lustre/projects/hpcsupport/steinbac/20180119-prepping-deconvolution-pipeline/cschmied/snakemake-workflows/spim_registration/timelapsedefine_czi.bsh (No such file or directory)
```
@schmiedc can you comment?

**Comment by schmiedc** [comment]
Hi,

the path seems wrong: 
/snakemake-workflows/spim_registration/timelapsedefine_czi.bsh
instead should be:
/snakemake-workflows/spim_registration/timelapse/define_czi.bsh

please check the path where you specify the bean shell scripts.
I guess you just miss a "/".

# bean shell scripts and Snakefile
  bsh_directory: "/projects/pilot_spim/Christopher/snakemake-workflows/spim_registration/timelapse/",

Cheers,
Christopher

**Comment by psteinb** [comment]
Aha, ok, then I suggest that I harden the Snakefile against these kind 
of errors. I'll first try to merge #27 though.

**Comment by schmiedc** [comment]
That would be great! Thanks a lot!
