### ISSUE TITLE
supporting luxendo file format within the snakefile

### ISSUE THREAD

**Issue by psteinb** [mpicbg-scicomp/snakemake-workflows#28]
Let's try to remove any shell scripts if possible. For example [this one](https://github.com/mpicbg-scicomp/snakemake-workflows/blob/master/spim_registration/tools/luxendo_resave/submit-jobs)

@schmiedc Can you point me to any resource describing this file format?

**Comment by schmiedc** [comment]
That is fine with me. I can give you example data. I will send you the link plus a description via Email.

**Comment by psteinb** [comment]
Ok, I will document it here then, so that possible contributors have a 
chance to follow our steps.

**Comment by schmiedc** [comment]
Sure, I can also reproduce the description here:

The luxendo files are saved as .h5 files. The key difference for the luxendo system ist that it has 2 detection objectives that are mirrored in respect to each other. An example dataset looks like this for example: 

3 views
1 channel
2 detection directions (Cam_Left and Cam_Right)

Each view and channel would then be saved in a different subdirectory. 
With the following naming scheme: stack_{view}_channel_{channel}

> ExampleDataset
>> stack_0_channel_0
>> stack_1_channel_0
>> stack_2_channel_0

The subdirectories then contain the individual .h5 files with the following naming scheme:
Cam_{left/right}_{timepoint#}.h5

The individual .h5 files can be opened with the HDF5 plugin (update site: http://sites.imagej.net/Ronneber/).

**Comment by psteinb** [comment]
Thanks for documenting this. Looks like this will be a small challenge 
to incorporate into the Snakefile.

**Comment by schmiedc** [comment]
Yes, I agree. I would rather drop it entirely or rather put it into a different project. The luxendo system comes with its own processing workflow. I integrated it more for comparing the quality of the images. So it is not so important that we cover that aspect as well.

**Comment by schmiedc** [comment]
The question here is also how we treat the entire "tools" folder. This is basically just a work around for all these file formats (.czi, ome-tiff, luxendo .h5). Its just to get them into .tif in case there is an aspect of their format that I cannot use directly with the multiview reconstruction application.

**Comment by psteinb** [comment]
Interesting. Well, that is a question for the community rather than to 
me. Whatever is decided to be supported by this package should be 
documented. If anything is not supported, it shouldn't be part of the 
repo - to be quite frank. It's simply a matter of separation of concern.

@mcahn @Xqua @spimager @stevenedwards Would you be interested in being 
able to process luxendo files with this pipeline?

**Comment by schmiedc** [comment]
I agree! Sounds good :)

**Comment by mcahn** [comment]
Hard to say -- we don't own a Luxendo yet, although we might in the
future.  Then it would be up to the users to decide how they want to
process things.  (I'm the sysadmin).

Matthew

**Comment by Xqua** [comment]
I don't plan on using the Luxendo scopes in the forseeable future, I've had access to the Keller lab scopes or Zeiss Z1. 
So I might not be the best person to ask ^^

**Comment by psteinb** [comment]
ok, then let's leave the support for luxendo files as it is. In case anyone needs proper support and is willing to invest some time with us. Please reopen this issue.
