### ISSUE TITLE
unavailable test data for the Automated Multiview Reconstruction workflow

### ISSUE THREAD

**Issue by sebherbert** [mpicbg-scicomp/snakemake-workflows#34]
Hi,

I would like to test the Automated Multiview Reconstruction workflow pipeline on our HPC but I can't access the test dataset and Fiji version [advertised on the imagej.net page](https://imagej.net/plugins/automated-workflow-for-parallel-multiview-reconstruction) at the provided address: [http://tomancak-srv1.mpi-cbg.de/~schmied/](http://tomancak-srv1.mpi-cbg.de/~schmied/) Maybe the link has changed?
I can try with the last Fiji version but a test dataset would be very useful to make sure that the overall workflow is properly set for our infrastructure before adapting it for our large dataset.

Cheers,
Sebastien

**Comment by schmiedc** [comment]
Hi,

sorry for the broken link. I setup a zenodo repo with the Fiji version and the test dataset. Let me know if that works for you: https://doi.org/10.5281/zenodo.6338071

I will fix the link.

Cheers,
Christopher

**Comment by sebherbert** [comment]
Thanks a lot! I've downloaded the data, all seems good so far. 
I'll let you know if I have other issues.
